# -*- coding: utf-8 -*-
"""Hnadling-Tag-Diversity (Libraries).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JAsqIxKRWMw2WAAYy2UQLkqqlnkiNmQn
"""

walk_length = 10
num_walks = 60
dimensions = 128
window = 10
min_count = 1
num_workers = 4
sg = 1
epochs = 20
alpha = 1e-3
p = 1
q = 0.5
seed = 42


node2vec_instance = Node2Vec(
    G,
    dimensions=dimensions,
    walk_length=walk_length ,
    num_walks=num_walks,
    workers=num_workers,
    p = p,
    q = q,
    seed = seed,
    weight_key = 'weight'
  )

model = node2vec_instance.fit(
    window=window,
    min_count=min_count,
    sg=sg,
    compute_loss=True,
    epochs = epochs,
    alpha = alpha,
    batch_words=4,
  )

tag_embeddings = {node: model.wv[node] for node in G.nodes()}
tag_names = list(tag_embeddings.keys())
Node2vec_embeddings = np.array(list(tag_embeddings.values()))