# -*- coding: utf-8 -*-
"""Hnadling-Tag-Diversity (Libraries).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JAsqIxKRWMw2WAAYy2UQLkqqlnkiNmQn
"""

posts_0 = copy.deepcopy(posts)
tags_0 = copy.deepcopy(tags)

co_occurrence_matrix = np.zeros((len(tags_0), len(tags_0)))

for post in posts_0:
    post_tags = set(post)
    for tag1 in post_tags:
        for tag2 in post_tags:
            if tag1 != tag2:
                index1 = tags_0.index(tag1)
                index2 = tags_0.index(tag2)
                co_occurrence_matrix[index1, index2] += 1
                co_occurrence_matrix[index2, index1] += 1

G = nx.Graph()
for i in range(len(tags_0)):
    for j in range(i + 1, len(tags_0)):
        if co_occurrence_matrix[i][j] > 0:
            tag1 = tags[i]
            tag2 = tags[j]
            weight = co_occurrence_matrix[i][j]
            G.add_edge(tag1, tag2, weight=weight)